language: java

after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1c4dc8e7520585524f45
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

